apiVersion: apps/v1
kind: Deployment
metadata:
  name: kessler-backend-deployment
  namespace: {{.Values.namespace}}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.backend.port }}
        command:
        - ./kessler-backend-go
        envFrom:
        - configMapRef:
            name: kessler-public-config
        - secretRef:
            name: kessler-private-config
        livenessProbe:
          httpGet:
            path: /v2/search
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
