apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kessler-frontend-cert
  namespace: kessler-prod
spec:
  secretName: kessler-frontend-cert
  issuerRef:
    name: kessler-letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - k8s-kessler.kessler.xyz
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
