apiVersion: apps/v1
kind: Deployment
metadata:
  name: kessler-frontend-deployment
  namespace: {{.Values.namespace}}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      {{/* hostNetwork: true */}}
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.frontend.port }}
        command:
        - npm
        - run
        - start
        {{/* - dev # changing to dev to test why npm run start isnt incorperating the .env files. */}}
        envFrom:
        - configMapRef:
            name: kessler-public-config
        - secretRef:
            name: kessler-private-config
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
