apiVersion: v1
kind: Service
metadata:
  name: kessler-frontend-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: frontend
  ports: 
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort:  {{ .Values.frontend.port }}
