apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kessler-ingress-frontend
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/issuer: kessler-letsencrypt-issuer
  labels:
    app: kessler
  namespace: {{.Values.namespace}}
spec:
  rules:
  - host: {{ .Values.frontend.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kessler-frontend-service
            port:
              number: {{ .Values.frontend.port }}
  tls:
  - hosts:
    - {{ .Values.frontend.domain }}
    secretName: kessler-frontend-cert
