apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kessler-letsencrypt-issuer
  namespace: {{.Values.namespace}}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{.Values.certManager.email}}
    privateKeySecretRef:
      name: kessler-letsencrypt-issuer-private-key
    solvers:
    - http01:
        ingress:
          class: traefik 
