apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kessler-letsencrypt-issuer
  namespace: {{.Values.namespace}}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{.Values.certManager.email}} # replace for your valid email
    privateKeySecretRef:
      name: kessler-letsencrypt-secretkey
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik
