services:
  mimir:
    image: grafana/otel-lgtm:latest
    # container_name: mimir
    ports:
      - 4317:4317
      - 4318:4318
      - 3009:3000
    restart: unless-stopped
# - 4317: OpenTelemetry GRPC endpoint
#
#  - 4318: OpenTelemetry HTTP endpoint
#  - 3000: Grafana. User: admin, password: admin
